### ISSUE TITLE
Splitting keithley_gui into a separate Python package

### ISSUE THREAD

**Issue by quaeritis** [OE-FET/customxepr#12]
Hi SamSchott,

I packed the keithley_gui into a separate Python package.
Is so far only the most necessary for the GUI to start.
I think it makes sense to do this so keithley_gui can be used independently of CustomXepr.

repo: https://github.com/quaeritis/Ktransfer2600

With best regards,
quaeritis

**Comment by samschott** [comment]
Hi quaeritis,

Yes, this makes sense to me. keithley_gui will work as a standalone, apart from the common config module and some dependencies from utils.

Note however that the GUI may look different than expected because CustomXepr tweaks the PyQt style globally on startup. Those changes should be subtle but may include a different appearance of the status bar and the figure widget.

Best,
Sam

**Comment by quaeritis** [comment]
would a joint development of Ktransfer2600 be possible?
Otherwise, I think it would be difficult to transfer customXepr/keithley_gui changes to Ktransfer2600.

I'm aware of the problem of PyQt style. However, this should be resolved without much effort.

**Comment by samschott** [comment]
Yes, of course. I have been thinking of splitting off the mercury and keithley UIs as separate packages and have moved all UI tweaks and settings to the individual modules in the dev branch. That will simplify joint development.

One will also need separate config files, and I will need to adapt CustomXepr to use those. I likely won't have time to do it next week, but feel free to fork CustomXepr and make the changes.

**Comment by quaeritis** [comment]
As I said I have the changes so far only for keithley UIs. Unfortunately, I created that from master branch. (repo: https://github.com/quaeritis/Ktransfer2600)

I could do that again starting from dev but then it would be better if the new resulting repo is used for the further development of keithley UIs. Otherwise it is very difficult to transfer changes made in keithley_gui.

Now the question is, should I wait for you to make changes in keithley_gui or can I create a "new" repo for the keithley UIs from the dev branch?

**Comment by samschott** [comment]
Please wait until I have made the appropriate changes, it might end up being a bit of a mess otherwise:

1) I will simplify the UI modifications and remove the dark theme entirely in the dev branch (PyQt may in the future support native dark modes of some operating systems such as macOS Mojave, at which point one may reintroduce modifications of plot appearances).

2) I will simplify the config module code. It still carries a lot of baggage from Spyder which is not needed for our simple use case. This is also a chance to remove all module / package specific code from "config.base". Reusing the config code between packages will then only require changes to "config.main". 

3) Create config and utils subfolders for mercury_gui and keithley_gui.

4) Split off mercury_gui and keithley_gui as separate packages.

As I said, this may take a while, through I am already halfway through 1) and 2).

**Comment by samschott** [comment]
All done. You'll find the repos at [https://github.com/OE-FET/mercuryitc](https://github.com/OE-FET/mercuryitc) and [https://github.com/OE-FET/keithleygui](https://github.com/OE-FET/keithleygui).
